
version: 2

sources:
  - name: sourcelayer
    tables:
      - name: CustomerCreateRaw
        description: "This table has all the raw data  in the form of JOSN received from the source system"
        columns:
            - name: messageid
              tests:
                  - not_null
            - name: balance
              tests:
                  - not_null
            - name: customer
              tests: 
                  - not_null
                  
  - name: flattendatalayer
    tables:
      - name: CustomerCreateFlattendata
        description: "Raw json from the Source table is parsed and transafomed into final flatten table"
        columns:
          - name: guid
            description: this column acts like primary key of the table
            tests:
                - not_null
                - unique
          - name: customer_name
            description: customer full name is stored in this column
            type: String
            tests:
                - not_null  
          - name : customer_gender
            tests:
                - not_null
          - name: customer_phone
            tests:
                - not_null
          - name: customer_email
            meta:
                sensitive: true
            tests:
                - not_null


  - name : demotable 
    tables:
      - name: Test
      - name: department
      - name: dept-gsb
      