
version: 2

sources:
  - name: Sorucelayer
    tables:
      - name: CustomerCreateRaw
      - name: CustomerCreateRaw_error_records
  - name : demotable 
    tables:
      - name: Test
      - name: department
      - name: dept-gsb
      